### ISSUE TITLE
Merge back upstream!

### ISSUE THREAD

**Issue by rposborne** [pallymore/wkhtmltopdf-heroku-edge#1]
@pallymore now that we have rights on the original project lets move this back!

**Comment by pallymore** [comment]
will do :)

**Comment by rposborne** [comment]
Keep everything as is. Just revert names.   I think we will need to to update the versions numbers since the upstream gem is already at 1.0.0   I think we either do a 2.12.x or 12.x to ensure we don't cause weird dependency issues for folks.

**Comment by pallymore** [comment]
hello @rposborne  I have created a pull request in the original repo https://github.com/rposborne/wkhtmltopdf-heroku/pull/16  

Could you merge it and push it to Rubygems? 

Thanks!

**Comment by rposborne** [comment]
Merged and Released.   Maybe add a deprecated note?
